// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_grepl_impl
LogicalVector fast_grepl_impl(const std::string& pattern, const StringVector& x, bool ignore_case, int nthreads);
RcppExport SEXP _fast_string_fast_grepl_impl(SEXP patternSEXP, SEXP xSEXP, SEXP ignore_caseSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_grepl_impl(pattern, x, ignore_case, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fast_fixed_impl
LogicalVector fast_fixed_impl(const std::string& pattern, const StringVector& x, bool ignore_case, int nthreads);
RcppExport SEXP _fast_string_fast_fixed_impl(SEXP patternSEXP, SEXP xSEXP, SEXP ignore_caseSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fixed_impl(pattern, x, ignore_case, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fast_regex_sub_impl
CharacterVector fast_regex_sub_impl(const std::string& pattern, const std::string& replacement, const StringVector& x, bool ignore_case, bool global, int nthreads);
RcppExport SEXP _fast_string_fast_regex_sub_impl(SEXP patternSEXP, SEXP replacementSEXP, SEXP xSEXP, SEXP ignore_caseSEXP, SEXP globalSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type replacement(replacementSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    Rcpp::traits::input_parameter< bool >::type global(globalSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_regex_sub_impl(pattern, replacement, x, ignore_case, global, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fast_fixed_gsub_all_impl
CharacterVector fast_fixed_gsub_all_impl(const StringVector& patterns, const StringVector& replacements, const StringVector& x, bool ignore_case, bool sequential, int nthreads);
RcppExport SEXP _fast_string_fast_fixed_gsub_all_impl(SEXP patternsSEXP, SEXP replacementsSEXP, SEXP xSEXP, SEXP ignore_caseSEXP, SEXP sequentialSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type patterns(patternsSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type replacements(replacementsSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    Rcpp::traits::input_parameter< bool >::type sequential(sequentialSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fixed_gsub_all_impl(patterns, replacements, x, ignore_case, sequential, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fast_regex_gsub_all_impl
CharacterVector fast_regex_gsub_all_impl(const StringVector& patterns, const StringVector& replacements, const StringVector& x, bool ignore_case, bool sequential, int nthreads);
RcppExport SEXP _fast_string_fast_regex_gsub_all_impl(SEXP patternsSEXP, SEXP replacementsSEXP, SEXP xSEXP, SEXP ignore_caseSEXP, SEXP sequentialSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type patterns(patternsSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type replacements(replacementsSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    Rcpp::traits::input_parameter< bool >::type sequential(sequentialSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_regex_gsub_all_impl(patterns, replacements, x, ignore_case, sequential, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fast_fixed_sub_impl
CharacterVector fast_fixed_sub_impl(const std::string& pattern, const std::string& replacement, const StringVector& x, bool ignore_case, bool global, int nthreads);
RcppExport SEXP _fast_string_fast_fixed_sub_impl(SEXP patternSEXP, SEXP replacementSEXP, SEXP xSEXP, SEXP ignore_caseSEXP, SEXP globalSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type replacement(replacementSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    Rcpp::traits::input_parameter< bool >::type global(globalSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fixed_sub_impl(pattern, replacement, x, ignore_case, global, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fast_format_date_impl
CharacterVector fast_format_date_impl(const NumericVector& x, int format_code);
RcppExport SEXP _fast_string_fast_format_date_impl(SEXP xSEXP, SEXP format_codeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type format_code(format_codeSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_format_date_impl(x, format_code));
    return rcpp_result_gen;
END_RCPP
}
// fast_format_date_parts_impl
CharacterVector fast_format_date_parts_impl(const IntegerVector& year, const IntegerVector& month, const IntegerVector& day, int format_code);
RcppExport SEXP _fast_string_fast_format_date_parts_impl(SEXP yearSEXP, SEXP monthSEXP, SEXP daySEXP, SEXP format_codeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type year(yearSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type month(monthSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type day(daySEXP);
    Rcpp::traits::input_parameter< int >::type format_code(format_codeSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_format_date_parts_impl(year, month, day, format_code));
    return rcpp_result_gen;
END_RCPP
}
// fast_parse_date_impl
NumericVector fast_parse_date_impl(const StringVector& x, int format_code);
RcppExport SEXP _fast_string_fast_parse_date_impl(SEXP xSEXP, SEXP format_codeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type format_code(format_codeSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_parse_date_impl(x, format_code));
    return rcpp_result_gen;
END_RCPP
}
// fast_date_parts_impl
List fast_date_parts_impl(const NumericVector& x);
RcppExport SEXP _fast_string_fast_date_parts_impl(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_date_parts_impl(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_jaro_winkler_impl
NumericVector fast_jaro_winkler_impl(const StringVector& a, const StringVector& b, double p, int nthreads, bool use_bytes);
RcppExport SEXP _fast_string_fast_jaro_winkler_impl(SEXP aSEXP, SEXP bSEXP, SEXP pSEXP, SEXP nthreadsSEXP, SEXP use_bytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_bytes(use_bytesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_jaro_winkler_impl(a, b, p, nthreads, use_bytes));
    return rcpp_result_gen;
END_RCPP
}
// fast_jaro_winkler_matrix_impl
NumericMatrix fast_jaro_winkler_matrix_impl(const StringVector& a, const StringVector& b, double p, int nthreads, bool use_bytes);
RcppExport SEXP _fast_string_fast_jaro_winkler_matrix_impl(SEXP aSEXP, SEXP bSEXP, SEXP pSEXP, SEXP nthreadsSEXP, SEXP use_bytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_bytes(use_bytesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_jaro_winkler_matrix_impl(a, b, p, nthreads, use_bytes));
    return rcpp_result_gen;
END_RCPP
}
// fast_jaro_winkler_tokens_impl
NumericVector fast_jaro_winkler_tokens_impl(const StringVector& a, const StringVector& b, double p, double extra_penalty, bool contractions, int nthreads);
RcppExport SEXP _fast_string_fast_jaro_winkler_tokens_impl(SEXP aSEXP, SEXP bSEXP, SEXP pSEXP, SEXP extra_penaltySEXP, SEXP contractionsSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type extra_penalty(extra_penaltySEXP);
    Rcpp::traits::input_parameter< bool >::type contractions(contractionsSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_jaro_winkler_tokens_impl(a, b, p, extra_penalty, contractions, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fast_soundex_impl
CharacterVector fast_soundex_impl(const StringVector& x);
RcppExport SEXP _fast_string_fast_soundex_impl(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_soundex_impl(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_nysiis_impl
CharacterVector fast_nysiis_impl(const StringVector& x);
RcppExport SEXP _fast_string_fast_nysiis_impl(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_nysiis_impl(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_double_metaphone_impl
List fast_double_metaphone_impl(const StringVector& x);
RcppExport SEXP _fast_string_fast_double_metaphone_impl(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_double_metaphone_impl(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_caverphone_impl
CharacterVector fast_caverphone_impl(const StringVector& x);
RcppExport SEXP _fast_string_fast_caverphone_impl(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_caverphone_impl(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_trimws_impl
CharacterVector fast_trimws_impl(const StringVector& x, int which);
RcppExport SEXP _fast_string_fast_trimws_impl(SEXP xSEXP, SEXP whichSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type which(whichSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_trimws_impl(x, which));
    return rcpp_result_gen;
END_RCPP
}
// fast_substr_impl
CharacterVector fast_substr_impl(const StringVector& x, const IntegerVector& start, const IntegerVector& stop, bool native_utf8);
RcppExport SEXP _fast_string_fast_substr_impl(SEXP xSEXP, SEXP startSEXP, SEXP stopSEXP, SEXP native_utf8SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type stop(stopSEXP);
    Rcpp::traits::input_parameter< bool >::type native_utf8(native_utf8SEXP);
    rcpp_result_gen = Rcpp::wrap(fast_substr_impl(x, start, stop, native_utf8));
    return rcpp_result_gen;
END_RCPP
}
// fast_nchar_impl
IntegerVector fast_nchar_impl(const StringVector& x, int type, bool allow_na, bool native_utf8);
RcppExport SEXP _fast_string_fast_nchar_impl(SEXP xSEXP, SEXP typeSEXP, SEXP allow_naSEXP, SEXP native_utf8SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    Rcpp::traits::input_parameter< bool >::type allow_na(allow_naSEXP);
    Rcpp::traits::input_parameter< bool >::type native_utf8(native_utf8SEXP);
    rcpp_result_gen = Rcpp::wrap(fast_nchar_impl(x, type, allow_na, native_utf8));
    return rcpp_result_gen;
END_RCPP
}
// fast_chartr_impl
CharacterVector fast_chartr_impl(const std::string& old_chars, const std::string& new_chars, const StringVector& x);
RcppExport SEXP _fast_string_fast_chartr_impl(SEXP old_charsSEXP, SEXP new_charsSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type old_chars(old_charsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type new_chars(new_charsSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_chartr_impl(old_chars, new_chars, x));
    return rcpp_result_gen;
END_RCPP
}
// fast_fuzz_ratio_impl
NumericVector fast_fuzz_ratio_impl(const StringVector& a, const StringVector& b, bool full_process, int nthreads);
RcppExport SEXP _fast_string_fast_fuzz_ratio_impl(SEXP aSEXP, SEXP bSEXP, SEXP full_processSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool >::type full_process(full_processSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fuzz_ratio_impl(a, b, full_process, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fast_fuzz_partial_ratio_impl
NumericVector fast_fuzz_partial_ratio_impl(const StringVector& a, const StringVector& b, bool full_process, int nthreads);
RcppExport SEXP _fast_string_fast_fuzz_partial_ratio_impl(SEXP aSEXP, SEXP bSEXP, SEXP full_processSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool >::type full_process(full_processSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fuzz_partial_ratio_impl(a, b, full_process, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fast_fuzz_token_sort_ratio_impl
NumericVector fast_fuzz_token_sort_ratio_impl(const StringVector& a, const StringVector& b, bool full_process, int nthreads);
RcppExport SEXP _fast_string_fast_fuzz_token_sort_ratio_impl(SEXP aSEXP, SEXP bSEXP, SEXP full_processSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool >::type full_process(full_processSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fuzz_token_sort_ratio_impl(a, b, full_process, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fast_fuzz_token_set_ratio_impl
NumericVector fast_fuzz_token_set_ratio_impl(const StringVector& a, const StringVector& b, bool full_process, int nthreads);
RcppExport SEXP _fast_string_fast_fuzz_token_set_ratio_impl(SEXP aSEXP, SEXP bSEXP, SEXP full_processSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< bool >::type full_process(full_processSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fuzz_token_set_ratio_impl(a, b, full_process, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fast_fuzzy_top_n_impl
List fast_fuzzy_top_n_impl(const StringVector& x, const StringVector& table, int method, int top_n, double p, double min_score, int max_distance, bool match_na, int nthreads, bool use_bytes);
RcppExport SEXP _fast_string_fast_fuzzy_top_n_impl(SEXP xSEXP, SEXP tableSEXP, SEXP methodSEXP, SEXP top_nSEXP, SEXP pSEXP, SEXP min_scoreSEXP, SEXP max_distanceSEXP, SEXP match_naSEXP, SEXP nthreadsSEXP, SEXP use_bytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type table(tableSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type top_n(top_nSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type min_score(min_scoreSEXP);
    Rcpp::traits::input_parameter< int >::type max_distance(max_distanceSEXP);
    Rcpp::traits::input_parameter< bool >::type match_na(match_naSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_bytes(use_bytesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fuzzy_top_n_impl(x, table, method, top_n, p, min_score, max_distance, match_na, nthreads, use_bytes));
    return rcpp_result_gen;
END_RCPP
}
// fast_levenshtein_impl
NumericVector fast_levenshtein_impl(const StringVector& a, const StringVector& b, int nthreads, bool use_bytes);
RcppExport SEXP _fast_string_fast_levenshtein_impl(SEXP aSEXP, SEXP bSEXP, SEXP nthreadsSEXP, SEXP use_bytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_bytes(use_bytesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_levenshtein_impl(a, b, nthreads, use_bytes));
    return rcpp_result_gen;
END_RCPP
}
// fast_levenshtein_matrix_impl
NumericMatrix fast_levenshtein_matrix_impl(const StringVector& a, const StringVector& b, int nthreads, bool use_bytes);
RcppExport SEXP _fast_string_fast_levenshtein_matrix_impl(SEXP aSEXP, SEXP bSEXP, SEXP nthreadsSEXP, SEXP use_bytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_bytes(use_bytesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_levenshtein_matrix_impl(a, b, nthreads, use_bytes));
    return rcpp_result_gen;
END_RCPP
}
// fast_osa_distance_impl
NumericVector fast_osa_distance_impl(const StringVector& a, const StringVector& b, int nthreads, bool use_bytes);
RcppExport SEXP _fast_string_fast_osa_distance_impl(SEXP aSEXP, SEXP bSEXP, SEXP nthreadsSEXP, SEXP use_bytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_bytes(use_bytesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_osa_distance_impl(a, b, nthreads, use_bytes));
    return rcpp_result_gen;
END_RCPP
}
// fast_osa_distance_matrix_impl
NumericMatrix fast_osa_distance_matrix_impl(const StringVector& a, const StringVector& b, int nthreads, bool use_bytes);
RcppExport SEXP _fast_string_fast_osa_distance_matrix_impl(SEXP aSEXP, SEXP bSEXP, SEXP nthreadsSEXP, SEXP use_bytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_bytes(use_bytesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_osa_distance_matrix_impl(a, b, nthreads, use_bytes));
    return rcpp_result_gen;
END_RCPP
}
// fast_damerau_levenshtein_impl
NumericVector fast_damerau_levenshtein_impl(const StringVector& a, const StringVector& b, int nthreads, bool use_bytes);
RcppExport SEXP _fast_string_fast_damerau_levenshtein_impl(SEXP aSEXP, SEXP bSEXP, SEXP nthreadsSEXP, SEXP use_bytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_bytes(use_bytesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_damerau_levenshtein_impl(a, b, nthreads, use_bytes));
    return rcpp_result_gen;
END_RCPP
}
// fast_damerau_levenshtein_matrix_impl
NumericMatrix fast_damerau_levenshtein_matrix_impl(const StringVector& a, const StringVector& b, int nthreads, bool use_bytes);
RcppExport SEXP _fast_string_fast_damerau_levenshtein_matrix_impl(SEXP aSEXP, SEXP bSEXP, SEXP nthreadsSEXP, SEXP use_bytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_bytes(use_bytesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_damerau_levenshtein_matrix_impl(a, b, nthreads, use_bytes));
    return rcpp_result_gen;
END_RCPP
}
// fast_hamming_impl
NumericVector fast_hamming_impl(const StringVector& a, const StringVector& b, int nthreads, bool use_bytes);
RcppExport SEXP _fast_string_fast_hamming_impl(SEXP aSEXP, SEXP bSEXP, SEXP nthreadsSEXP, SEXP use_bytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_bytes(use_bytesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_hamming_impl(a, b, nthreads, use_bytes));
    return rcpp_result_gen;
END_RCPP
}
// fast_edit_similarity_impl
NumericVector fast_edit_similarity_impl(const StringVector& a, const StringVector& b, int method, int nthreads, bool use_bytes);
RcppExport SEXP _fast_string_fast_edit_similarity_impl(SEXP aSEXP, SEXP bSEXP, SEXP methodSEXP, SEXP nthreadsSEXP, SEXP use_bytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_bytes(use_bytesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_edit_similarity_impl(a, b, method, nthreads, use_bytes));
    return rcpp_result_gen;
END_RCPP
}
// fast_levenshtein_within_impl
LogicalVector fast_levenshtein_within_impl(const StringVector& a, const StringVector& b, int max_distance, int nthreads, bool use_bytes);
RcppExport SEXP _fast_string_fast_levenshtein_within_impl(SEXP aSEXP, SEXP bSEXP, SEXP max_distanceSEXP, SEXP nthreadsSEXP, SEXP use_bytesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type max_distance(max_distanceSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_bytes(use_bytesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_levenshtein_within_impl(a, b, max_distance, nthreads, use_bytes));
    return rcpp_result_gen;
END_RCPP
}
// fast_jaccard_impl
NumericVector fast_jaccard_impl(const StringVector& a, const StringVector& b, int q, int nthreads);
RcppExport SEXP _fast_string_fast_jaccard_impl(SEXP aSEXP, SEXP bSEXP, SEXP qSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_jaccard_impl(a, b, q, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fast_jaccard_matrix_impl
NumericMatrix fast_jaccard_matrix_impl(const StringVector& a, const StringVector& b, int q, int nthreads);
RcppExport SEXP _fast_string_fast_jaccard_matrix_impl(SEXP aSEXP, SEXP bSEXP, SEXP qSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_jaccard_matrix_impl(a, b, q, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fast_dice_impl
NumericVector fast_dice_impl(const StringVector& a, const StringVector& b, int q, int nthreads);
RcppExport SEXP _fast_string_fast_dice_impl(SEXP aSEXP, SEXP bSEXP, SEXP qSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_dice_impl(a, b, q, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fast_dice_matrix_impl
NumericMatrix fast_dice_matrix_impl(const StringVector& a, const StringVector& b, int q, int nthreads);
RcppExport SEXP _fast_string_fast_dice_matrix_impl(SEXP aSEXP, SEXP bSEXP, SEXP qSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_dice_matrix_impl(a, b, q, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fast_tversky_impl
NumericVector fast_tversky_impl(const StringVector& a, const StringVector& b, int q, double alpha, double beta, int nthreads);
RcppExport SEXP _fast_string_fast_tversky_impl(SEXP aSEXP, SEXP bSEXP, SEXP qSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_tversky_impl(a, b, q, alpha, beta, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// fast_tversky_matrix_impl
NumericMatrix fast_tversky_matrix_impl(const StringVector& a, const StringVector& b, int q, double alpha, double beta, int nthreads);
RcppExport SEXP _fast_string_fast_tversky_matrix_impl(SEXP aSEXP, SEXP bSEXP, SEXP qSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_tversky_matrix_impl(a, b, q, alpha, beta, nthreads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fast_string_fast_grepl_impl", (DL_FUNC) &_fast_string_fast_grepl_impl, 4},
    {"_fast_string_fast_fixed_impl", (DL_FUNC) &_fast_string_fast_fixed_impl, 4},
    {"_fast_string_fast_regex_sub_impl", (DL_FUNC) &_fast_string_fast_regex_sub_impl, 6},
    {"_fast_string_fast_fixed_gsub_all_impl", (DL_FUNC) &_fast_string_fast_fixed_gsub_all_impl, 6},
    {"_fast_string_fast_regex_gsub_all_impl", (DL_FUNC) &_fast_string_fast_regex_gsub_all_impl, 6},
    {"_fast_string_fast_fixed_sub_impl", (DL_FUNC) &_fast_string_fast_fixed_sub_impl, 6},
    {"_fast_string_fast_format_date_impl", (DL_FUNC) &_fast_string_fast_format_date_impl, 2},
    {"_fast_string_fast_format_date_parts_impl", (DL_FUNC) &_fast_string_fast_format_date_parts_impl, 4},
    {"_fast_string_fast_parse_date_impl", (DL_FUNC) &_fast_string_fast_parse_date_impl, 2},
    {"_fast_string_fast_date_parts_impl", (DL_FUNC) &_fast_string_fast_date_parts_impl, 1},
    {"_fast_string_fast_jaro_winkler_impl", (DL_FUNC) &_fast_string_fast_jaro_winkler_impl, 5},
    {"_fast_string_fast_jaro_winkler_matrix_impl", (DL_FUNC) &_fast_string_fast_jaro_winkler_matrix_impl, 5},
    {"_fast_string_fast_jaro_winkler_tokens_impl", (DL_FUNC) &_fast_string_fast_jaro_winkler_tokens_impl, 6},
    {"_fast_string_fast_soundex_impl", (DL_FUNC) &_fast_string_fast_soundex_impl, 1},
    {"_fast_string_fast_nysiis_impl", (DL_FUNC) &_fast_string_fast_nysiis_impl, 1},
    {"_fast_string_fast_double_metaphone_impl", (DL_FUNC) &_fast_string_fast_double_metaphone_impl, 1},
    {"_fast_string_fast_caverphone_impl", (DL_FUNC) &_fast_string_fast_caverphone_impl, 1},
    {"_fast_string_fast_trimws_impl", (DL_FUNC) &_fast_string_fast_trimws_impl, 2},
    {"_fast_string_fast_substr_impl", (DL_FUNC) &_fast_string_fast_substr_impl, 4},
    {"_fast_string_fast_nchar_impl", (DL_FUNC) &_fast_string_fast_nchar_impl, 4},
    {"_fast_string_fast_chartr_impl", (DL_FUNC) &_fast_string_fast_chartr_impl, 3},
    {"_fast_string_fast_fuzz_ratio_impl", (DL_FUNC) &_fast_string_fast_fuzz_ratio_impl, 4},
    {"_fast_string_fast_fuzz_partial_ratio_impl", (DL_FUNC) &_fast_string_fast_fuzz_partial_ratio_impl, 4},
    {"_fast_string_fast_fuzz_token_sort_ratio_impl", (DL_FUNC) &_fast_string_fast_fuzz_token_sort_ratio_impl, 4},
    {"_fast_string_fast_fuzz_token_set_ratio_impl", (DL_FUNC) &_fast_string_fast_fuzz_token_set_ratio_impl, 4},
    {"_fast_string_fast_fuzzy_top_n_impl", (DL_FUNC) &_fast_string_fast_fuzzy_top_n_impl, 10},
    {"_fast_string_fast_levenshtein_impl", (DL_FUNC) &_fast_string_fast_levenshtein_impl, 4},
    {"_fast_string_fast_levenshtein_matrix_impl", (DL_FUNC) &_fast_string_fast_levenshtein_matrix_impl, 4},
    {"_fast_string_fast_osa_distance_impl", (DL_FUNC) &_fast_string_fast_osa_distance_impl, 4},
    {"_fast_string_fast_osa_distance_matrix_impl", (DL_FUNC) &_fast_string_fast_osa_distance_matrix_impl, 4},
    {"_fast_string_fast_damerau_levenshtein_impl", (DL_FUNC) &_fast_string_fast_damerau_levenshtein_impl, 4},
    {"_fast_string_fast_damerau_levenshtein_matrix_impl", (DL_FUNC) &_fast_string_fast_damerau_levenshtein_matrix_impl, 4},
    {"_fast_string_fast_hamming_impl", (DL_FUNC) &_fast_string_fast_hamming_impl, 4},
    {"_fast_string_fast_edit_similarity_impl", (DL_FUNC) &_fast_string_fast_edit_similarity_impl, 5},
    {"_fast_string_fast_levenshtein_within_impl", (DL_FUNC) &_fast_string_fast_levenshtein_within_impl, 5},
    {"_fast_string_fast_jaccard_impl", (DL_FUNC) &_fast_string_fast_jaccard_impl, 4},
    {"_fast_string_fast_jaccard_matrix_impl", (DL_FUNC) &_fast_string_fast_jaccard_matrix_impl, 4},
    {"_fast_string_fast_dice_impl", (DL_FUNC) &_fast_string_fast_dice_impl, 4},
    {"_fast_string_fast_dice_matrix_impl", (DL_FUNC) &_fast_string_fast_dice_matrix_impl, 4},
    {"_fast_string_fast_tversky_impl", (DL_FUNC) &_fast_string_fast_tversky_impl, 6},
    {"_fast_string_fast_tversky_matrix_impl", (DL_FUNC) &_fast_string_fast_tversky_matrix_impl, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_fast_string(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
