// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_grepl_impl
LogicalVector fast_grepl_impl(const std::string& pattern, const StringVector& x, bool ignore_case);
RcppExport SEXP _fgrepl_fast_grepl_impl(SEXP patternSEXP, SEXP xSEXP, SEXP ignore_caseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_grepl_impl(pattern, x, ignore_case));
    return rcpp_result_gen;
END_RCPP
}
// fast_fixed_impl
LogicalVector fast_fixed_impl(const std::string& pattern, const StringVector& x, bool ignore_case);
RcppExport SEXP _fgrepl_fast_fixed_impl(SEXP patternSEXP, SEXP xSEXP, SEXP ignore_caseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fixed_impl(pattern, x, ignore_case));
    return rcpp_result_gen;
END_RCPP
}
// fast_regex_sub_impl
CharacterVector fast_regex_sub_impl(const std::string& pattern, const std::string& replacement, const StringVector& x, bool ignore_case, bool global);
RcppExport SEXP _fgrepl_fast_regex_sub_impl(SEXP patternSEXP, SEXP replacementSEXP, SEXP xSEXP, SEXP ignore_caseSEXP, SEXP globalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type replacement(replacementSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    Rcpp::traits::input_parameter< bool >::type global(globalSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_regex_sub_impl(pattern, replacement, x, ignore_case, global));
    return rcpp_result_gen;
END_RCPP
}
// fast_fixed_gsub_all_impl
CharacterVector fast_fixed_gsub_all_impl(const StringVector& patterns, const StringVector& replacements, const StringVector& x, bool ignore_case, bool sequential);
RcppExport SEXP _fgrepl_fast_fixed_gsub_all_impl(SEXP patternsSEXP, SEXP replacementsSEXP, SEXP xSEXP, SEXP ignore_caseSEXP, SEXP sequentialSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type patterns(patternsSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type replacements(replacementsSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    Rcpp::traits::input_parameter< bool >::type sequential(sequentialSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fixed_gsub_all_impl(patterns, replacements, x, ignore_case, sequential));
    return rcpp_result_gen;
END_RCPP
}
// fast_regex_gsub_all_impl
CharacterVector fast_regex_gsub_all_impl(const StringVector& patterns, const StringVector& replacements, const StringVector& x, bool ignore_case, bool sequential);
RcppExport SEXP _fgrepl_fast_regex_gsub_all_impl(SEXP patternsSEXP, SEXP replacementsSEXP, SEXP xSEXP, SEXP ignore_caseSEXP, SEXP sequentialSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type patterns(patternsSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type replacements(replacementsSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    Rcpp::traits::input_parameter< bool >::type sequential(sequentialSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_regex_gsub_all_impl(patterns, replacements, x, ignore_case, sequential));
    return rcpp_result_gen;
END_RCPP
}
// fast_fixed_sub_impl
CharacterVector fast_fixed_sub_impl(const std::string& pattern, const std::string& replacement, const StringVector& x, bool ignore_case, bool global);
RcppExport SEXP _fgrepl_fast_fixed_sub_impl(SEXP patternSEXP, SEXP replacementSEXP, SEXP xSEXP, SEXP ignore_caseSEXP, SEXP globalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type replacement(replacementSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    Rcpp::traits::input_parameter< bool >::type global(globalSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fixed_sub_impl(pattern, replacement, x, ignore_case, global));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fgrepl_fast_grepl_impl", (DL_FUNC) &_fgrepl_fast_grepl_impl, 3},
    {"_fgrepl_fast_fixed_impl", (DL_FUNC) &_fgrepl_fast_fixed_impl, 3},
    {"_fgrepl_fast_regex_sub_impl", (DL_FUNC) &_fgrepl_fast_regex_sub_impl, 5},
    {"_fgrepl_fast_fixed_gsub_all_impl", (DL_FUNC) &_fgrepl_fast_fixed_gsub_all_impl, 5},
    {"_fgrepl_fast_regex_gsub_all_impl", (DL_FUNC) &_fgrepl_fast_regex_gsub_all_impl, 5},
    {"_fgrepl_fast_fixed_sub_impl", (DL_FUNC) &_fgrepl_fast_fixed_sub_impl, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_fgrepl(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
