// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_grepl_impl
LogicalVector fast_grepl_impl(const std::string& pattern, const StringVector& x, bool ignore_case);
RcppExport SEXP _fast_string_fast_grepl_impl(SEXP patternSEXP, SEXP xSEXP, SEXP ignore_caseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_grepl_impl(pattern, x, ignore_case));
    return rcpp_result_gen;
END_RCPP
}
// fast_fixed_impl
LogicalVector fast_fixed_impl(const std::string& pattern, const StringVector& x, bool ignore_case);
RcppExport SEXP _fast_string_fast_fixed_impl(SEXP patternSEXP, SEXP xSEXP, SEXP ignore_caseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fixed_impl(pattern, x, ignore_case));
    return rcpp_result_gen;
END_RCPP
}
// fast_regex_sub_impl
CharacterVector fast_regex_sub_impl(const std::string& pattern, const std::string& replacement, const StringVector& x, bool ignore_case, bool global);
RcppExport SEXP _fast_string_fast_regex_sub_impl(SEXP patternSEXP, SEXP replacementSEXP, SEXP xSEXP, SEXP ignore_caseSEXP, SEXP globalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type replacement(replacementSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    Rcpp::traits::input_parameter< bool >::type global(globalSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_regex_sub_impl(pattern, replacement, x, ignore_case, global));
    return rcpp_result_gen;
END_RCPP
}
// fast_fixed_gsub_all_impl
CharacterVector fast_fixed_gsub_all_impl(const StringVector& patterns, const StringVector& replacements, const StringVector& x, bool ignore_case, bool sequential);
RcppExport SEXP _fast_string_fast_fixed_gsub_all_impl(SEXP patternsSEXP, SEXP replacementsSEXP, SEXP xSEXP, SEXP ignore_caseSEXP, SEXP sequentialSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type patterns(patternsSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type replacements(replacementsSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    Rcpp::traits::input_parameter< bool >::type sequential(sequentialSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fixed_gsub_all_impl(patterns, replacements, x, ignore_case, sequential));
    return rcpp_result_gen;
END_RCPP
}
// fast_regex_gsub_all_impl
CharacterVector fast_regex_gsub_all_impl(const StringVector& patterns, const StringVector& replacements, const StringVector& x, bool ignore_case, bool sequential);
RcppExport SEXP _fast_string_fast_regex_gsub_all_impl(SEXP patternsSEXP, SEXP replacementsSEXP, SEXP xSEXP, SEXP ignore_caseSEXP, SEXP sequentialSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type patterns(patternsSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type replacements(replacementsSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    Rcpp::traits::input_parameter< bool >::type sequential(sequentialSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_regex_gsub_all_impl(patterns, replacements, x, ignore_case, sequential));
    return rcpp_result_gen;
END_RCPP
}
// fast_fixed_sub_impl
CharacterVector fast_fixed_sub_impl(const std::string& pattern, const std::string& replacement, const StringVector& x, bool ignore_case, bool global);
RcppExport SEXP _fast_string_fast_fixed_sub_impl(SEXP patternSEXP, SEXP replacementSEXP, SEXP xSEXP, SEXP ignore_caseSEXP, SEXP globalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type pattern(patternSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type replacement(replacementSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type ignore_case(ignore_caseSEXP);
    Rcpp::traits::input_parameter< bool >::type global(globalSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fixed_sub_impl(pattern, replacement, x, ignore_case, global));
    return rcpp_result_gen;
END_RCPP
}
// fast_format_date_impl
CharacterVector fast_format_date_impl(const NumericVector& x, int format_code);
RcppExport SEXP _fast_string_fast_format_date_impl(SEXP xSEXP, SEXP format_codeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type format_code(format_codeSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_format_date_impl(x, format_code));
    return rcpp_result_gen;
END_RCPP
}
// fast_format_date_parts_impl
CharacterVector fast_format_date_parts_impl(const IntegerVector& year, const IntegerVector& month, const IntegerVector& day, int format_code);
RcppExport SEXP _fast_string_fast_format_date_parts_impl(SEXP yearSEXP, SEXP monthSEXP, SEXP daySEXP, SEXP format_codeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type year(yearSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type month(monthSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type day(daySEXP);
    Rcpp::traits::input_parameter< int >::type format_code(format_codeSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_format_date_parts_impl(year, month, day, format_code));
    return rcpp_result_gen;
END_RCPP
}
// fast_parse_date_impl
NumericVector fast_parse_date_impl(const StringVector& x, int format_code);
RcppExport SEXP _fast_string_fast_parse_date_impl(SEXP xSEXP, SEXP format_codeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type format_code(format_codeSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_parse_date_impl(x, format_code));
    return rcpp_result_gen;
END_RCPP
}
// fast_date_parts_impl
List fast_date_parts_impl(const NumericVector& x);
RcppExport SEXP _fast_string_fast_date_parts_impl(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_date_parts_impl(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_jaro_winkler_impl
NumericVector fast_jaro_winkler_impl(const StringVector& a, const StringVector& b, double p);
RcppExport SEXP _fast_string_fast_jaro_winkler_impl(SEXP aSEXP, SEXP bSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_jaro_winkler_impl(a, b, p));
    return rcpp_result_gen;
END_RCPP
}
// fast_jaro_winkler_matrix_impl
NumericMatrix fast_jaro_winkler_matrix_impl(const StringVector& a, const StringVector& b, double p);
RcppExport SEXP _fast_string_fast_jaro_winkler_matrix_impl(SEXP aSEXP, SEXP bSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_jaro_winkler_matrix_impl(a, b, p));
    return rcpp_result_gen;
END_RCPP
}
// fast_jaro_winkler_tokens_impl
NumericVector fast_jaro_winkler_tokens_impl(const StringVector& a, const StringVector& b, double p, double extra_penalty, bool contractions);
RcppExport SEXP _fast_string_fast_jaro_winkler_tokens_impl(SEXP aSEXP, SEXP bSEXP, SEXP pSEXP, SEXP extra_penaltySEXP, SEXP contractionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type extra_penalty(extra_penaltySEXP);
    Rcpp::traits::input_parameter< bool >::type contractions(contractionsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_jaro_winkler_tokens_impl(a, b, p, extra_penalty, contractions));
    return rcpp_result_gen;
END_RCPP
}
// fast_soundex_impl
CharacterVector fast_soundex_impl(const StringVector& x);
RcppExport SEXP _fast_string_fast_soundex_impl(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_soundex_impl(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_nysiis_impl
CharacterVector fast_nysiis_impl(const StringVector& x);
RcppExport SEXP _fast_string_fast_nysiis_impl(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_nysiis_impl(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_double_metaphone_impl
List fast_double_metaphone_impl(const StringVector& x);
RcppExport SEXP _fast_string_fast_double_metaphone_impl(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_double_metaphone_impl(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_caverphone_impl
CharacterVector fast_caverphone_impl(const StringVector& x);
RcppExport SEXP _fast_string_fast_caverphone_impl(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_caverphone_impl(x));
    return rcpp_result_gen;
END_RCPP
}
// fast_trimws_impl
CharacterVector fast_trimws_impl(const StringVector& x, int which);
RcppExport SEXP _fast_string_fast_trimws_impl(SEXP xSEXP, SEXP whichSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type which(whichSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_trimws_impl(x, which));
    return rcpp_result_gen;
END_RCPP
}
// fast_substr_impl
CharacterVector fast_substr_impl(const StringVector& x, const IntegerVector& start, const IntegerVector& stop);
RcppExport SEXP _fast_string_fast_substr_impl(SEXP xSEXP, SEXP startSEXP, SEXP stopSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type stop(stopSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_substr_impl(x, start, stop));
    return rcpp_result_gen;
END_RCPP
}
// fast_nchar_impl
IntegerVector fast_nchar_impl(const StringVector& x, int type, bool allow_na);
RcppExport SEXP _fast_string_fast_nchar_impl(SEXP xSEXP, SEXP typeSEXP, SEXP allow_naSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    Rcpp::traits::input_parameter< bool >::type allow_na(allow_naSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_nchar_impl(x, type, allow_na));
    return rcpp_result_gen;
END_RCPP
}
// fast_chartr_impl
CharacterVector fast_chartr_impl(const std::string& old_chars, const std::string& new_chars, const StringVector& x);
RcppExport SEXP _fast_string_fast_chartr_impl(SEXP old_charsSEXP, SEXP new_charsSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type old_chars(old_charsSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type new_chars(new_charsSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_chartr_impl(old_chars, new_chars, x));
    return rcpp_result_gen;
END_RCPP
}
// fast_fuzz_ratio_impl
NumericVector fast_fuzz_ratio_impl(const StringVector& a, const StringVector& b);
RcppExport SEXP _fast_string_fast_fuzz_ratio_impl(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fuzz_ratio_impl(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fast_fuzz_partial_ratio_impl
NumericVector fast_fuzz_partial_ratio_impl(const StringVector& a, const StringVector& b);
RcppExport SEXP _fast_string_fast_fuzz_partial_ratio_impl(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fuzz_partial_ratio_impl(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fast_fuzz_token_sort_ratio_impl
NumericVector fast_fuzz_token_sort_ratio_impl(const StringVector& a, const StringVector& b);
RcppExport SEXP _fast_string_fast_fuzz_token_sort_ratio_impl(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fuzz_token_sort_ratio_impl(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fast_fuzz_token_set_ratio_impl
NumericVector fast_fuzz_token_set_ratio_impl(const StringVector& a, const StringVector& b);
RcppExport SEXP _fast_string_fast_fuzz_token_set_ratio_impl(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_fuzz_token_set_ratio_impl(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fast_levenshtein_impl
NumericVector fast_levenshtein_impl(const StringVector& a, const StringVector& b);
RcppExport SEXP _fast_string_fast_levenshtein_impl(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_levenshtein_impl(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fast_levenshtein_matrix_impl
NumericMatrix fast_levenshtein_matrix_impl(const StringVector& a, const StringVector& b);
RcppExport SEXP _fast_string_fast_levenshtein_matrix_impl(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_levenshtein_matrix_impl(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fast_damerau_levenshtein_impl
NumericVector fast_damerau_levenshtein_impl(const StringVector& a, const StringVector& b);
RcppExport SEXP _fast_string_fast_damerau_levenshtein_impl(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_damerau_levenshtein_impl(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fast_damerau_levenshtein_matrix_impl
NumericMatrix fast_damerau_levenshtein_matrix_impl(const StringVector& a, const StringVector& b);
RcppExport SEXP _fast_string_fast_damerau_levenshtein_matrix_impl(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_damerau_levenshtein_matrix_impl(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fast_hamming_impl
NumericVector fast_hamming_impl(const StringVector& a, const StringVector& b);
RcppExport SEXP _fast_string_fast_hamming_impl(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_hamming_impl(a, b));
    return rcpp_result_gen;
END_RCPP
}
// fast_jaccard_impl
NumericVector fast_jaccard_impl(const StringVector& a, const StringVector& b, int q);
RcppExport SEXP _fast_string_fast_jaccard_impl(SEXP aSEXP, SEXP bSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_jaccard_impl(a, b, q));
    return rcpp_result_gen;
END_RCPP
}
// fast_jaccard_matrix_impl
NumericMatrix fast_jaccard_matrix_impl(const StringVector& a, const StringVector& b, int q);
RcppExport SEXP _fast_string_fast_jaccard_matrix_impl(SEXP aSEXP, SEXP bSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_jaccard_matrix_impl(a, b, q));
    return rcpp_result_gen;
END_RCPP
}
// fast_dice_impl
NumericVector fast_dice_impl(const StringVector& a, const StringVector& b, int q);
RcppExport SEXP _fast_string_fast_dice_impl(SEXP aSEXP, SEXP bSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_dice_impl(a, b, q));
    return rcpp_result_gen;
END_RCPP
}
// fast_dice_matrix_impl
NumericMatrix fast_dice_matrix_impl(const StringVector& a, const StringVector& b, int q);
RcppExport SEXP _fast_string_fast_dice_matrix_impl(SEXP aSEXP, SEXP bSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_dice_matrix_impl(a, b, q));
    return rcpp_result_gen;
END_RCPP
}
// fast_tversky_impl
NumericVector fast_tversky_impl(const StringVector& a, const StringVector& b, int q, double alpha, double beta);
RcppExport SEXP _fast_string_fast_tversky_impl(SEXP aSEXP, SEXP bSEXP, SEXP qSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_tversky_impl(a, b, q, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// fast_tversky_matrix_impl
NumericMatrix fast_tversky_matrix_impl(const StringVector& a, const StringVector& b, int q, double alpha, double beta);
RcppExport SEXP _fast_string_fast_tversky_matrix_impl(SEXP aSEXP, SEXP bSEXP, SEXP qSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const StringVector& >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_tversky_matrix_impl(a, b, q, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fast_string_fast_grepl_impl", (DL_FUNC) &_fast_string_fast_grepl_impl, 3},
    {"_fast_string_fast_fixed_impl", (DL_FUNC) &_fast_string_fast_fixed_impl, 3},
    {"_fast_string_fast_regex_sub_impl", (DL_FUNC) &_fast_string_fast_regex_sub_impl, 5},
    {"_fast_string_fast_fixed_gsub_all_impl", (DL_FUNC) &_fast_string_fast_fixed_gsub_all_impl, 5},
    {"_fast_string_fast_regex_gsub_all_impl", (DL_FUNC) &_fast_string_fast_regex_gsub_all_impl, 5},
    {"_fast_string_fast_fixed_sub_impl", (DL_FUNC) &_fast_string_fast_fixed_sub_impl, 5},
    {"_fast_string_fast_format_date_impl", (DL_FUNC) &_fast_string_fast_format_date_impl, 2},
    {"_fast_string_fast_format_date_parts_impl", (DL_FUNC) &_fast_string_fast_format_date_parts_impl, 4},
    {"_fast_string_fast_parse_date_impl", (DL_FUNC) &_fast_string_fast_parse_date_impl, 2},
    {"_fast_string_fast_date_parts_impl", (DL_FUNC) &_fast_string_fast_date_parts_impl, 1},
    {"_fast_string_fast_jaro_winkler_impl", (DL_FUNC) &_fast_string_fast_jaro_winkler_impl, 3},
    {"_fast_string_fast_jaro_winkler_matrix_impl", (DL_FUNC) &_fast_string_fast_jaro_winkler_matrix_impl, 3},
    {"_fast_string_fast_jaro_winkler_tokens_impl", (DL_FUNC) &_fast_string_fast_jaro_winkler_tokens_impl, 5},
    {"_fast_string_fast_soundex_impl", (DL_FUNC) &_fast_string_fast_soundex_impl, 1},
    {"_fast_string_fast_nysiis_impl", (DL_FUNC) &_fast_string_fast_nysiis_impl, 1},
    {"_fast_string_fast_double_metaphone_impl", (DL_FUNC) &_fast_string_fast_double_metaphone_impl, 1},
    {"_fast_string_fast_caverphone_impl", (DL_FUNC) &_fast_string_fast_caverphone_impl, 1},
    {"_fast_string_fast_trimws_impl", (DL_FUNC) &_fast_string_fast_trimws_impl, 2},
    {"_fast_string_fast_substr_impl", (DL_FUNC) &_fast_string_fast_substr_impl, 3},
    {"_fast_string_fast_nchar_impl", (DL_FUNC) &_fast_string_fast_nchar_impl, 3},
    {"_fast_string_fast_chartr_impl", (DL_FUNC) &_fast_string_fast_chartr_impl, 3},
    {"_fast_string_fast_fuzz_ratio_impl", (DL_FUNC) &_fast_string_fast_fuzz_ratio_impl, 2},
    {"_fast_string_fast_fuzz_partial_ratio_impl", (DL_FUNC) &_fast_string_fast_fuzz_partial_ratio_impl, 2},
    {"_fast_string_fast_fuzz_token_sort_ratio_impl", (DL_FUNC) &_fast_string_fast_fuzz_token_sort_ratio_impl, 2},
    {"_fast_string_fast_fuzz_token_set_ratio_impl", (DL_FUNC) &_fast_string_fast_fuzz_token_set_ratio_impl, 2},
    {"_fast_string_fast_levenshtein_impl", (DL_FUNC) &_fast_string_fast_levenshtein_impl, 2},
    {"_fast_string_fast_levenshtein_matrix_impl", (DL_FUNC) &_fast_string_fast_levenshtein_matrix_impl, 2},
    {"_fast_string_fast_damerau_levenshtein_impl", (DL_FUNC) &_fast_string_fast_damerau_levenshtein_impl, 2},
    {"_fast_string_fast_damerau_levenshtein_matrix_impl", (DL_FUNC) &_fast_string_fast_damerau_levenshtein_matrix_impl, 2},
    {"_fast_string_fast_hamming_impl", (DL_FUNC) &_fast_string_fast_hamming_impl, 2},
    {"_fast_string_fast_jaccard_impl", (DL_FUNC) &_fast_string_fast_jaccard_impl, 3},
    {"_fast_string_fast_jaccard_matrix_impl", (DL_FUNC) &_fast_string_fast_jaccard_matrix_impl, 3},
    {"_fast_string_fast_dice_impl", (DL_FUNC) &_fast_string_fast_dice_impl, 3},
    {"_fast_string_fast_dice_matrix_impl", (DL_FUNC) &_fast_string_fast_dice_matrix_impl, 3},
    {"_fast_string_fast_tversky_impl", (DL_FUNC) &_fast_string_fast_tversky_impl, 5},
    {"_fast_string_fast_tversky_matrix_impl", (DL_FUNC) &_fast_string_fast_tversky_matrix_impl, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_fast_string(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
