{
  "hash": "36390aed41f3538f3667231358409a23",
  "result": {
    "engine": "knitr",
    "markdown": "# A worked record-linkage pipeline {#sec-workflow}\n\n\n\nThis chapter strings every piece from @sec-quickstart together into a\nsingle, realistic linkage pipeline: an incoming batch of records needs to\nbe matched against a reference database. It's the same shape of problem\n`examples_data_linkage.R` in the repo demonstrates, written out here as a\nnarrative.\n\nThe batch arrives the way batches actually arrive — names in mixed case\nwith punctuation, dates as strings in a local format, a load timestamp per\nrow, a junk record that should never have been sent, and the same person\nsubmitted twice. Getting from that to a defensible set of links is eight\nsteps, and most of the functions in this package show up in one of them.\n\n## The data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincoming <- data.frame(\n    id       = 1:7,\n    name     = c(\"  JOHN O'BRIEN  \", \"MARY-JANE SMITH\", \"ROBERT BROWN\",\n                 \"Kyle John Haynes\", \"Hans Müller\", \"UNKNOWN 00000000\",\n                 \"JOHN OBRIEN\"),\n    dob      = c(\"15/03/1985\", \"22/07/1990\", \"01/12/1975\", \"05/01/1988\",\n                 \"09/09/1971\", \"01/01/1900\", \"15/03/1985\"),\n    received = c(\"2024-06-18 09:15:00\", \"2024-06-18 09:17:42\",\n                 \"2024-06-18 11:02:10\", \"2024-06-18 11:45:00\",\n                 \"2024-06-18 12:00:00\", \"2024-06-18 12:30:00\",\n                 \"2024-06-18 14:20:00\"),\n    stringsAsFactors = FALSE\n)\n\nreference <- data.frame(\n    ref_id = 101:106,\n    name   = c(\"JON OBRIEN\", \"MARYANN SMITH\", \"ROB BROWN\", \"JOHN BRIEN\",\n               \"Haynes John Kyle\", \"Hans Mueller\"),\n    dob    = as.Date(c(\"1985-03-14\", \"1990-07-20\", \"1975-12-02\",\n                       \"1985-03-15\", \"1988-01-05\", \"1971-09-09\")),\n    stringsAsFactors = FALSE\n)\n\nincoming\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id             name        dob            received\n1  1   JOHN O'BRIEN   15/03/1985 2024-06-18 09:15:00\n2  2  MARY-JANE SMITH 22/07/1990 2024-06-18 09:17:42\n3  3     ROBERT BROWN 01/12/1975 2024-06-18 11:02:10\n4  4 Kyle John Haynes 05/01/1988 2024-06-18 11:45:00\n5  5      Hans Müller 09/09/1971 2024-06-18 12:00:00\n6  6 UNKNOWN 00000000 01/01/1900 2024-06-18 12:30:00\n7  7      JOHN OBRIEN 15/03/1985 2024-06-18 14:20:00\n```\n\n\n:::\n\n```{.r .cell-code}\nreference\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ref_id             name        dob\n1    101       JON OBRIEN 1985-03-14\n2    102    MARYANN SMITH 1990-07-20\n3    103        ROB BROWN 1975-12-02\n4    104       JOHN BRIEN 1985-03-15\n5    105 Haynes John Kyle 1988-01-05\n6    106     Hans Mueller 1971-09-09\n```\n\n\n:::\n:::\n\n\nSeven incoming records, six reference records, deliberately messy:\ninconsistent casing, stray whitespace, punctuation, typos, a near-duplicate\nin the reference file (`\"JOHN BRIEN\"` vs. `\"JON OBRIEN\"`), a fully\nreordered multi-token name (`\"Kyle John Haynes\"` vs. `\"Haynes John Kyle\"`),\na German name spelled two ways (`\"Hans Müller\"` vs. `\"Hans Mueller\"`), a\nplaceholder record (`\"UNKNOWN 00000000\"`), and one person submitted twice\nin the same batch (ids 1 and 7).\n\n## Step 1: profile before you match\n\nThe cheapest way to improve a linkage run is to not feed it rubbish.\n`fcount()` counts non-overlapping matches per element, which makes\ncolumn-level quality rules one vectorised call each: how many digits are in\na name field (a name with digits is almost always a placeholder or a\nconcatenated identifier), and how many tokens a name has.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincoming$n_digits <- fcount(\"[0-9]\", incoming$name)\nincoming$n_tokens <- fcount(\" +\", ftrimws(incoming$name)) + 1L\n\nincoming[, c(\"id\", \"name\", \"n_digits\", \"n_tokens\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id             name n_digits n_tokens\n1  1   JOHN O'BRIEN          0        2\n2  2  MARY-JANE SMITH        0        2\n3  3     ROBERT BROWN        0        2\n4  4 Kyle John Haynes        0        3\n5  5      Hans Müller        0        2\n6  6 UNKNOWN 00000000        8        2\n7  7      JOHN OBRIEN        0        2\n```\n\n\n:::\n:::\n\n\nRecord 6 is the placeholder. `fcount()` is the counting counterpart to\n`fgrepl()` — same PCRE2 and prepared-fixed-string engines, same parallel\ndispatch — and replaces the `vapply(gregexpr(...), length, ...)` idiom,\nwhich allocates a match-position vector per row just to take its length and\nneeds two explicit branches to reproduce `fcount()`'s `NA`-and-zero\nhandling:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nidentical(\n    fcount(\"[0-9]\", incoming$name),\n    vapply(gregexpr(\"[0-9]\", incoming$name),\n           function(m) if (is.na(m[1])) NA_integer_\n                       else if (m[1] < 0L) 0L else length(m),\n           integer(1))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n## Step 2: parse dates and timestamps\n\nThe batch carries dates as `DD/MM/YYYY` strings and a load timestamp per\nrow. `fas.Date()` and `fas.POSIXct()` parse one fixed, locale-free shape\neach — no format guessing, no timezone-database lookup.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincoming$dob_date    <- fas.Date(incoming$dob, \"dmy\")\nincoming$received_ts <- fas.POSIXct(incoming$received)\n\nincoming[, c(\"id\", \"dob\", \"dob_date\", \"received\", \"received_ts\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id        dob   dob_date            received         received_ts\n1  1 15/03/1985 1985-03-15 2024-06-18 09:15:00 2024-06-18 09:15:00\n2  2 22/07/1990 1990-07-22 2024-06-18 09:17:42 2024-06-18 09:17:42\n3  3 01/12/1975 1975-12-01 2024-06-18 11:02:10 2024-06-18 11:02:10\n4  4 05/01/1988 1988-01-05 2024-06-18 11:45:00 2024-06-18 11:45:00\n5  5 09/09/1971 1971-09-09 2024-06-18 12:00:00 2024-06-18 12:00:00\n6  6 01/01/1900 1900-01-01 2024-06-18 12:30:00 2024-06-18 12:30:00\n7  7 15/03/1985 1985-03-15 2024-06-18 14:20:00 2024-06-18 14:20:00\n```\n\n\n:::\n:::\n\n\nThe two functions differ in strictness, and it matters when you're deciding\nwhich one is allowed to silently accept bad input. `fas.Date()` validates\nfield ranges only (month 1-12, day 1-31), so an impossible calendar date\nrolls over; `fas.POSIXct()` validates the full calendar, including month\nlengths and leap years, and returns `NA`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfas.Date(\"29/02/2023\", \"dmy\")          # rolls over -- 2023 is not a leap year\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2023-03-01\"\n```\n\n\n:::\n\n```{.r .cell-code}\nfas.POSIXct(\"2023-02-29 08:00:00\")     # NA\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n:::\n\n\nSo `fas.POSIXct()` doubles as a validity check on the timestamp column, and\nan `NA` there is a legitimate reason to quarantine a row.\n\n## Step 3: normalise and quarantine\n\nStrip punctuation and whitespace inconsistencies *before* comparing, so the\ncomparison step measures genuine name similarity rather than formatting\nnoise — then set aside the rows the profile step flagged.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nincoming$name_clean <- fgsub(\" +\", \" \", fchartr(\"'-\", \"  \", ftrimws(incoming$name)))\nreference$name_clean <- fchartr(\"'-\", \"  \", ftrimws(reference$name))\n\nusable <- incoming$n_digits == 0L &\n    !is.na(incoming$dob_date) &\n    !is.na(incoming$received_ts)\n\nquarantine <- incoming[!usable, ]\nbatch      <- incoming[usable, ]\n\nbatch[, c(\"id\", \"name_clean\", \"dob_date\", \"received_ts\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id       name_clean   dob_date         received_ts\n1  1     JOHN O BRIEN 1985-03-15 2024-06-18 09:15:00\n2  2  MARY JANE SMITH 1990-07-22 2024-06-18 09:17:42\n3  3     ROBERT BROWN 1975-12-01 2024-06-18 11:02:10\n4  4 Kyle John Haynes 1988-01-05 2024-06-18 11:45:00\n5  5      Hans Müller 1971-09-09 2024-06-18 12:00:00\n7  7      JOHN OBRIEN 1985-03-15 2024-06-18 14:20:00\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(quarantine)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n\n(`jaro_winkler_tokens()` does its own internal punctuation stripping and\ncase-folding — see @sec-reference — but normalising up front keeps this\nexample explicit, and matters for `jaro_winkler()`/`jaro_winkler_matrix()`\nand the q-gram metrics, which don't.)\n\n## Step 4: collapse duplicates inside the batch\n\nIds 1 and 7 are the same person, sent twice. Deduplicating *before*\nmatching keeps a single incoming record from generating two competing links\nto the same reference row. The parsed timestamp decides which copy\nsurvives — last write wins.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbatch$dedupe_key <- paste(fgsub(\" \", \"\", toupper(batch$name_clean)), batch$dob_date)\nbatch[, c(\"id\", \"dedupe_key\", \"received_ts\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id                dedupe_key         received_ts\n1  1     JOHNOBRIEN 1985-03-15 2024-06-18 09:15:00\n2  2  MARYJANESMITH 1990-07-22 2024-06-18 09:17:42\n3  3    ROBERTBROWN 1975-12-01 2024-06-18 11:02:10\n4  4 KYLEJOHNHAYNES 1988-01-05 2024-06-18 11:45:00\n5  5     HANSMÜLLER 1971-09-09 2024-06-18 12:00:00\n7  7     JOHNOBRIEN 1985-03-15 2024-06-18 14:20:00\n```\n\n\n:::\n\n```{.r .cell-code}\nbatch <- batch[order(batch$dedupe_key, -as.numeric(batch$received_ts)), ]\nbatch <- batch[!duplicated(batch$dedupe_key), ]\nbatch <- batch[order(batch$id), ]\n\nbatch[, c(\"id\", \"name_clean\", \"dob_date\", \"received_ts\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id       name_clean   dob_date         received_ts\n2  2  MARY JANE SMITH 1990-07-22 2024-06-18 09:17:42\n3  3     ROBERT BROWN 1975-12-01 2024-06-18 11:02:10\n4  4 Kyle John Haynes 1988-01-05 2024-06-18 11:45:00\n5  5      Hans Müller 1971-09-09 2024-06-18 12:00:00\n7  7      JOHN OBRIEN 1985-03-15 2024-06-18 14:20:00\n```\n\n\n:::\n:::\n\n\nRecord 1 (09:15) is dropped in favour of record 7 (14:20). Note that this\nstep only catches duplicates that normalise to the *same* string —\ngenuinely fuzzy within-batch duplicates need the same scoring machinery as\nthe linkage itself, run with `batch` on both sides.\n\n## Step 5: block on more than one phonetic key\n\nComparing every incoming record against every reference record is\n$O(n \\times m)$ — fine at this toy scale, prohibitive at millions of rows.\n**Blocking** groups records by a cheap, coarse key first and only compares\nrecords *within* the same block.\n\nThe classic key is `soundex()` on a surname, but a single key inherits that\nscheme's blind spots. Two of the additions here exist precisely to cover\ndifferent ones:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngerman <- c(\"Müller\", \"Mueller\", \"Miller\", \"Meier\", \"Meyer\")\ndata.frame(\n    name    = german,\n    soundex = soundex(german),\n    refined = refined_soundex(german),\n    cologne = cologne(german)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     name soundex refined cologne\n1  Müller    M460   M8709     657\n2 Mueller    M460  M80709     657\n3  Miller    M460  M80709     657\n4   Meier    M600    M809      67\n5   Meyer    M600    M809      67\n```\n\n\n:::\n:::\n\n\nRead that table in the direction of *how much each key merges*. Classic\n`soundex()` does catch `\"Müller\"`/`\"Mueller\"` here — but only as a side\neffect of discarding vowels entirely, which is also why it drops\n`\"Miller\"` in with them and collapses `\"Meier\"`/`\"Meyer\"` to a single\n`M600`. That bluntness is the thing you're trying to get away from at\nscale: coarse keys make big blocks, and big blocks are what blocking\nexists to avoid.\n\n`refined_soundex()` is the precise end. It encodes vowels rather than\ndiscarding them and doesn't truncate, so blocks get smaller — but the\numlaut isn't an ASCII vowel it can encode, so it splits `\"Müller\"`\n(`M8709`) from `\"Mueller\"` (`M80709`) and on its own would never make that\npair a candidate. `cologne()` folds umlauts by design and gives both\n`657`, while staying coarse enough to pull `\"Miller\"` in too.\n\nNeither key is right on its own, and that's the point: running both and\nunioning the candidate sets recovers the specific pair the precise key\nmisses without adopting the coarse key's block sizes everywhere else.\n@sec-theory quantifies the selectivity difference across a wider surname\nlist.\n\nBecause names arrive in inconsistent token order, block on the phonetic\ncode of *every* token rather than a positional \"surname\" — a record is a\ncandidate if it shares any token code, within the same birth year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nblock_keys <- function(ids, names_vec, years, scheme) {\n    toks  <- strsplit(names_vec, \" +\")\n    codes <- scheme(unlist(toks))\n    out <- data.frame(\n        id    = rep(ids, lengths(toks)),\n        key   = paste0(codes, \":\", rep(years, lengths(toks))),\n        token = unlist(toks),\n        stringsAsFactors = FALSE\n    )\n    out[!is.na(codes) & nzchar(codes), ]\n}\n\ninc_year <- as.integer(format(batch$dob_date, \"%Y\"))\nref_year <- as.integer(format(reference$dob, \"%Y\"))\n\ninc_keys <- rbind(\n    transform(block_keys(batch$id, batch$name_clean, inc_year, refined_soundex),\n              scheme = \"refined_soundex\"),\n    transform(block_keys(batch$id, batch$name_clean, inc_year, cologne),\n              scheme = \"cologne\")\n)\nref_keys <- rbind(\n    transform(block_keys(reference$ref_id, reference$name_clean, ref_year, refined_soundex),\n              scheme = \"refined_soundex\"),\n    transform(block_keys(reference$ref_id, reference$name_clean, ref_year, cologne),\n              scheme = \"cologne\")\n)\nnames(ref_keys)[c(1, 3)] <- c(\"ref_id\", \"ref_token\")\n\nhead(inc_keys, 8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id          key  token          scheme\n1  2   M8090:1990   MARY refined_soundex\n2  2   J4080:1990   JANE refined_soundex\n3  2  S38060:1990  SMITH refined_soundex\n4  3 R901096:1975 ROBERT refined_soundex\n5  3   B1908:1975  BROWN refined_soundex\n6  4   K3070:1988   Kyle refined_soundex\n7  4    J408:1988   John refined_soundex\n8  4   H0803:1988 Haynes refined_soundex\n```\n\n\n:::\n:::\n\n\nThe whole exploded token vector is encoded in one vectorised call per\nscheme, so the per-token cost is a parallel C++ pass rather than an R-level\nloop over records.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhits  <- merge(inc_keys, ref_keys, by = c(\"key\", \"scheme\"))\npairs <- unique(hits[, c(\"id\", \"ref_id\")])\npairs <- pairs[order(pairs$id, pairs$ref_id), ]\n\nnrow(pairs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(batch) * nrow(reference)   # the full cross product this replaces\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 30\n```\n\n\n:::\n\n```{.r .cell-code}\npairs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   id ref_id\n10  2    102\n7   3    103\n4   4    105\n5   5    106\n1   7    101\n2   7    104\n```\n\n\n:::\n:::\n\n\nSix candidate pairs instead of thirty. At this scale that saving is\ncosmetic; the point is the ratio, which is what survives to five million\nrows — and that every true match is still in the set.\n\nKeeping the token alongside the key makes the blocking step auditable —\nyou can ask *why* any given pair is a candidate, which matters when you're\ntuning keys and need to know which one is carrying the recall:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(hits[hits$id == 5 & hits$ref_id == 106,\n            c(\"scheme\", \"token\", \"ref_token\", \"key\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            scheme  token ref_token       key\n5          cologne   Hans      Hans  068:1971\n9          cologne Müller   Mueller  657:1971\n13 refined_soundex   Hans      Hans H083:1971\n```\n\n\n:::\n:::\n\n\nNote what this says, and what it doesn't. The `\"Hans Müller\"` pair is\nreachable under *both* schemes, because the given name is identical and\n`refined_soundex()` blocks it happily. Cologne's contribution is the second\nrow: it is the only one of the two that also links the *surnames*\n(`\"Müller\"`/`\"Mueller\"` → `657`). On this batch that's redundant — but\ngiven names disagree across systems constantly (`\"Hans\"`/`\"Johann\"`/`\"H\"`),\nand when they do, that surname key is the only thing keeping the pair\nalive.\n\n## Step 6: score the candidates\n\nScore name similarity only among surviving candidates, with two\ndeliberately different metrics. `jaro_winkler_tokens()` compares names\ntoken by token and is insensitive to token order by construction.\n`cosine_similarity()` compares q-gram *frequency profiles* across the whole\nstring, so it is order-sensitive and weights repeated q-grams — an\nindependent signal rather than a restatement of the first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs$name_a  <- batch$name_clean[match(pairs$id, batch$id)]\npairs$name_b  <- reference$name_clean[match(pairs$ref_id, reference$ref_id)]\npairs$dob_gap <- abs(as.integer(\n    batch$dob_date[match(pairs$id, batch$id)] -\n    reference$dob[match(pairs$ref_id, reference$ref_id)]\n))\n\npairs$jw  <- jaro_winkler_tokens(pairs$name_a, pairs$name_b, ignore_case = TRUE)\npairs$cos <- cosine_similarity(toupper(pairs$name_a), toupper(pairs$name_b), q = 2)\n\npairs[order(pairs$id, -pairs$jw),\n      c(\"id\", \"name_a\", \"ref_id\", \"name_b\", \"jw\", \"cos\", \"dob_gap\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   id           name_a ref_id           name_b        jw       cos dob_gap\n10  2  MARY JANE SMITH    102    MARYANN SMITH 0.9525641 0.6943651       2\n7   3     ROBERT BROWN    103        ROB BROWN 0.9416667 0.7893522       1\n4   4 Kyle John Haynes    105 Haynes John Kyle 1.0000000 0.8666667       0\n5   5      Hans Müller    106     Hans Mueller 0.9142857 0.7272727       0\n2   7      JOHN OBRIEN    104       JOHN BRIEN 0.9800000 0.8432740       0\n1   7      JOHN OBRIEN    101       JON OBRIEN 0.9733333 0.8432740       1\n```\n\n\n:::\n:::\n\n\nThe two scores disagree in informative ways. `\"Kyle John Haynes\"` vs.\n`\"Haynes John Kyle\"` is a perfect `1.000` under token comparison — every\ntoken has an exact partner — but `0.867` under cosine, which sees the\nreordering as changed bigrams across token boundaries. That gap *is* the\ninformation: a high `jw` with a lower `cos` says \"same tokens, different\narrangement\", which is a different kind of evidence from \"same arrangement,\none typo\".\n\n## Step 7: decide, and admit ambiguity\n\nApply a cutoff to decide which candidate pairs are accepted as links. 0.85\nis a common starting point for Jaro-Winkler on names; the right value\ndepends on your data and how costly false positives/negatives are relative\nto each other — tune it against a labelled sample if you have one. The\ndate gap is a second field-level filter, tolerating a small typo in the day\nor month without accepting an unrelated birth date.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naccepted <- pairs[pairs$jw >= 0.85 & pairs$dob_gap <= 2, ]\naccepted <- accepted[order(accepted$id, -accepted$jw), ]\naccepted$ambiguous <- table(accepted$id)[as.character(accepted$id)] > 1L\n\naccepted[, c(\"id\", \"name_a\", \"ref_id\", \"name_b\", \"jw\", \"cos\", \"dob_gap\", \"ambiguous\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   id           name_a ref_id           name_b        jw       cos dob_gap ambiguous\n10  2  MARY JANE SMITH    102    MARYANN SMITH 0.9525641 0.6943651       2     FALSE\n7   3     ROBERT BROWN    103        ROB BROWN 0.9416667 0.7893522       1     FALSE\n4   4 Kyle John Haynes    105 Haynes John Kyle 1.0000000 0.8666667       0     FALSE\n5   5      Hans Müller    106     Hans Mueller 0.9142857 0.7272727       0     FALSE\n2   7      JOHN OBRIEN    104       JOHN BRIEN 0.9800000 0.8432740       0      TRUE\n1   7      JOHN OBRIEN    101       JON OBRIEN 0.9733333 0.8432740       1      TRUE\n```\n\n\n:::\n:::\n\n\nEvery incoming record links to its obvious match, including the fully\nreordered `\"Kyle John Haynes\"` → `\"Haynes John Kyle\"` pair — the one case\nin this dataset where plain `jaro_winkler()` would have scored well below\nthreshold and `jaro_winkler_tokens()` is doing real work — and the\n`\"Hans Müller\"` → `\"Hans Mueller\"` pair, which clears the threshold at\n`0.914` despite the umlaut, because token comparison is scoring the\ncharacters rather than a phonetic key.\n\nRecord 7 is the honest case. It has two surviving candidates, `0.980` and\n`0.973`, and *identical* cosine scores of `0.843`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbest   <- accepted[!duplicated(accepted$id), ]\nsecond <- accepted[duplicated(accepted$id), ]\nbest$margin <- best$jw - second$jw[match(best$id, second$id)]\n\nbest[, c(\"id\", \"name_a\", \"ref_id\", \"name_b\", \"jw\", \"cos\", \"margin\")]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   id           name_a ref_id           name_b        jw       cos      margin\n10  2  MARY JANE SMITH    102    MARYANN SMITH 0.9525641 0.6943651          NA\n7   3     ROBERT BROWN    103        ROB BROWN 0.9416667 0.7893522          NA\n4   4 Kyle John Haynes    105 Haynes John Kyle 1.0000000 0.8666667          NA\n5   5      Hans Müller    106     Hans Mueller 0.9142857 0.7272727          NA\n2   7      JOHN OBRIEN    104       JOHN BRIEN 0.9800000 0.8432740 0.006666667\n```\n\n\n:::\n:::\n\n\nA margin of 0.007 between the top two candidates is not a decision, it's a\ncoin toss with extra steps. The second metric doesn't break the tie here —\nit agrees — and that agreement is itself the finding: `\"JOHN OBRIEN\"` is\ngenuinely close to both `\"JOHN BRIEN\"` and `\"JON OBRIEN\"`, and no threshold\non this evidence can tell you which. The right output is a review queue,\nnot a link. Routing thin-margin pairs to clerical review, rather than\nletting `!duplicated()` silently pick the first row, is the difference\nbetween a linkage you can defend and one you can't.\n\n## Step 8: stamp the output\n\nDownstream loads need to know which batch they're looking at.\n`format_datetime()` writes the batch watermark without a timezone-database\nlookup, in UTC or at one fixed offset for a local-time report:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwatermark <- max(batch$received_ts)\n\nformat_datetime(watermark, \"rfc3339\")                        # UTC, for the audit log\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2024-06-18T14:20:00Z\"\n```\n\n\n:::\n\n```{.r .cell-code}\nformat_datetime(watermark, \"iso_offset\", offset = \"+10:00\")  # local time, for humans\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2024-06-19T00:20:00+10:00\"\n```\n\n\n:::\n\n```{.r .cell-code}\nformat_datetime(watermark, \"compact\")                        # sortable partition key\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"20240618142000\"\n```\n\n\n:::\n:::\n\n\n`\"iso_offset\"` applies one fixed numeric offset to every value — it is not\na timezone. It has no daylight-saving rules, so a batch spanning a DST\nboundary needs `base::format()` with a real timezone; for stamping a single\nload with a known offset, this is the cheap and correct tool.\n\n## Why the fast versions matter here\n\nSteps 1 and 2 are the ones that quietly dominate a real batch load: they\ntouch every row of every column, before any of the interesting matching\nwork starts. A single timed run on this machine, over 300,000 rows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nn  <- 3e5\nnm <- paste0(sample(c(\"John Smith\", \"Mary O'Brien\", \"Kyle J Haynes 12\"), n, TRUE),\n             \" \", sample(999, n, TRUE))\nts <- format(as.POSIXct(\"2024-06-18 09:15:00\", tz = \"UTC\") + sample(1e7, n), \"%Y-%m-%d %H:%M:%S\")\n\nsystem.time(vapply(gregexpr(\"[0-9]\", nm),\n                   function(m) if (m[1] < 0L) 0L else length(m), integer(1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   user  system elapsed \n   1.74    0.11    1.83 \n```\n\n\n:::\n\n```{.r .cell-code}\nsystem.time(fcount(\"[0-9]\", nm))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   user  system elapsed \n   0.02    0.00    0.01 \n```\n\n\n:::\n\n```{.r .cell-code}\nsystem.time(as.POSIXct(ts, tz = \"UTC\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   user  system elapsed \n   2.74    0.20    2.94 \n```\n\n\n:::\n\n```{.r .cell-code}\nsystem.time(fas.POSIXct(ts))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   user  system elapsed \n   0.01    0.00    0.02 \n```\n\n\n:::\n:::\n\n\nBoth are single runs on one machine and will vary with cores and input\nshape — @sec-benchmarks is the chapter with the reproducible harness, and\nit scales the comparison step of this exact pipeline shape up to 3 million\nrows.\n",
    "supporting": [
      "04-record-linkage-workflow_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}