# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_grepl_impl <- function(pattern, x, ignore_case) {
    .Call(`_fgrepl_fast_grepl_impl`, pattern, x, ignore_case)
}

fast_fixed_impl <- function(pattern, x, ignore_case) {
    .Call(`_fgrepl_fast_fixed_impl`, pattern, x, ignore_case)
}

