# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_grepl_impl <- function(pattern, x, ignore_case, nthreads) {
    .Call(`_fast_string_fast_grepl_impl`, pattern, x, ignore_case, nthreads)
}

fast_fixed_impl <- function(pattern, x, ignore_case, nthreads) {
    .Call(`_fast_string_fast_fixed_impl`, pattern, x, ignore_case, nthreads)
}

fast_regex_count_impl <- function(pattern, x, ignore_case, nthreads) {
    .Call(`_fast_string_fast_regex_count_impl`, pattern, x, ignore_case, nthreads)
}

fast_fixed_count_impl <- function(pattern, x, ignore_case, nthreads) {
    .Call(`_fast_string_fast_fixed_count_impl`, pattern, x, ignore_case, nthreads)
}

fast_regex_sub_impl <- function(pattern, replacement, x, ignore_case, global, nthreads) {
    .Call(`_fast_string_fast_regex_sub_impl`, pattern, replacement, x, ignore_case, global, nthreads)
}

fast_fixed_gsub_all_impl <- function(patterns, replacements, x, ignore_case, sequential, nthreads) {
    .Call(`_fast_string_fast_fixed_gsub_all_impl`, patterns, replacements, x, ignore_case, sequential, nthreads)
}

fast_regex_gsub_all_impl <- function(patterns, replacements, x, ignore_case, sequential, nthreads) {
    .Call(`_fast_string_fast_regex_gsub_all_impl`, patterns, replacements, x, ignore_case, sequential, nthreads)
}

fast_fixed_sub_impl <- function(pattern, replacement, x, ignore_case, global, nthreads) {
    .Call(`_fast_string_fast_fixed_sub_impl`, pattern, replacement, x, ignore_case, global, nthreads)
}

fast_format_date_impl <- function(x, format_code) {
    .Call(`_fast_string_fast_format_date_impl`, x, format_code)
}

fast_format_date_parts_impl <- function(year, month, day, format_code) {
    .Call(`_fast_string_fast_format_date_parts_impl`, year, month, day, format_code)
}

fast_parse_date_impl <- function(x, format_code) {
    .Call(`_fast_string_fast_parse_date_impl`, x, format_code)
}

fast_parse_datetime_impl <- function(x, format_code) {
    .Call(`_fast_string_fast_parse_datetime_impl`, x, format_code)
}

fast_format_datetime_impl <- function(x, format_code, offset_minutes) {
    .Call(`_fast_string_fast_format_datetime_impl`, x, format_code, offset_minutes)
}

fast_date_parts_impl <- function(x) {
    .Call(`_fast_string_fast_date_parts_impl`, x)
}

fast_jaro_winkler_impl <- function(a, b, p, nthreads, use_bytes) {
    .Call(`_fast_string_fast_jaro_winkler_impl`, a, b, p, nthreads, use_bytes)
}

fast_jaro_winkler_matrix_impl <- function(a, b, p, nthreads, use_bytes) {
    .Call(`_fast_string_fast_jaro_winkler_matrix_impl`, a, b, p, nthreads, use_bytes)
}

fast_jaro_winkler_tokens_impl <- function(a, b, p, extra_penalty, contractions, nthreads) {
    .Call(`_fast_string_fast_jaro_winkler_tokens_impl`, a, b, p, extra_penalty, contractions, nthreads)
}

fast_soundex_impl <- function(x) {
    .Call(`_fast_string_fast_soundex_impl`, x)
}

fast_nysiis_impl <- function(x) {
    .Call(`_fast_string_fast_nysiis_impl`, x)
}

fast_refined_soundex_impl <- function(x) {
    .Call(`_fast_string_fast_refined_soundex_impl`, x)
}

fast_cologne_impl <- function(x) {
    .Call(`_fast_string_fast_cologne_impl`, x)
}

fast_double_metaphone_impl <- function(x) {
    .Call(`_fast_string_fast_double_metaphone_impl`, x)
}

fast_caverphone_impl <- function(x) {
    .Call(`_fast_string_fast_caverphone_impl`, x)
}

fast_trimws_impl <- function(x, which) {
    .Call(`_fast_string_fast_trimws_impl`, x, which)
}

fast_substr_impl <- function(x, start, stop, native_utf8) {
    .Call(`_fast_string_fast_substr_impl`, x, start, stop, native_utf8)
}

fast_nchar_impl <- function(x, type, allow_na, native_utf8) {
    .Call(`_fast_string_fast_nchar_impl`, x, type, allow_na, native_utf8)
}

fast_chartr_impl <- function(old_chars, new_chars, x) {
    .Call(`_fast_string_fast_chartr_impl`, old_chars, new_chars, x)
}

fast_fuzz_ratio_impl <- function(a, b, full_process, nthreads) {
    .Call(`_fast_string_fast_fuzz_ratio_impl`, a, b, full_process, nthreads)
}

fast_fuzz_partial_ratio_impl <- function(a, b, full_process, nthreads) {
    .Call(`_fast_string_fast_fuzz_partial_ratio_impl`, a, b, full_process, nthreads)
}

fast_fuzz_token_sort_ratio_impl <- function(a, b, full_process, nthreads) {
    .Call(`_fast_string_fast_fuzz_token_sort_ratio_impl`, a, b, full_process, nthreads)
}

fast_fuzz_token_set_ratio_impl <- function(a, b, full_process, nthreads) {
    .Call(`_fast_string_fast_fuzz_token_set_ratio_impl`, a, b, full_process, nthreads)
}

fast_fuzzy_top_n_impl <- function(x, table, method, top_n, p, min_score, max_distance, match_na, nthreads, use_bytes) {
    .Call(`_fast_string_fast_fuzzy_top_n_impl`, x, table, method, top_n, p, min_score, max_distance, match_na, nthreads, use_bytes)
}

fast_levenshtein_impl <- function(a, b, nthreads, use_bytes) {
    .Call(`_fast_string_fast_levenshtein_impl`, a, b, nthreads, use_bytes)
}

fast_levenshtein_matrix_impl <- function(a, b, nthreads, use_bytes) {
    .Call(`_fast_string_fast_levenshtein_matrix_impl`, a, b, nthreads, use_bytes)
}

fast_osa_distance_impl <- function(a, b, nthreads, use_bytes) {
    .Call(`_fast_string_fast_osa_distance_impl`, a, b, nthreads, use_bytes)
}

fast_osa_distance_matrix_impl <- function(a, b, nthreads, use_bytes) {
    .Call(`_fast_string_fast_osa_distance_matrix_impl`, a, b, nthreads, use_bytes)
}

fast_damerau_levenshtein_impl <- function(a, b, nthreads, use_bytes) {
    .Call(`_fast_string_fast_damerau_levenshtein_impl`, a, b, nthreads, use_bytes)
}

fast_damerau_levenshtein_matrix_impl <- function(a, b, nthreads, use_bytes) {
    .Call(`_fast_string_fast_damerau_levenshtein_matrix_impl`, a, b, nthreads, use_bytes)
}

fast_hamming_impl <- function(a, b, nthreads, use_bytes) {
    .Call(`_fast_string_fast_hamming_impl`, a, b, nthreads, use_bytes)
}

fast_edit_similarity_impl <- function(a, b, method, nthreads, use_bytes) {
    .Call(`_fast_string_fast_edit_similarity_impl`, a, b, method, nthreads, use_bytes)
}

fast_levenshtein_within_impl <- function(a, b, max_distance, nthreads, use_bytes) {
    .Call(`_fast_string_fast_levenshtein_within_impl`, a, b, max_distance, nthreads, use_bytes)
}

fast_jaccard_impl <- function(a, b, q, nthreads) {
    .Call(`_fast_string_fast_jaccard_impl`, a, b, q, nthreads)
}

fast_jaccard_matrix_impl <- function(a, b, q, nthreads) {
    .Call(`_fast_string_fast_jaccard_matrix_impl`, a, b, q, nthreads)
}

fast_dice_impl <- function(a, b, q, nthreads) {
    .Call(`_fast_string_fast_dice_impl`, a, b, q, nthreads)
}

fast_dice_matrix_impl <- function(a, b, q, nthreads) {
    .Call(`_fast_string_fast_dice_matrix_impl`, a, b, q, nthreads)
}

fast_tversky_impl <- function(a, b, q, alpha, beta, nthreads) {
    .Call(`_fast_string_fast_tversky_impl`, a, b, q, alpha, beta, nthreads)
}

fast_tversky_matrix_impl <- function(a, b, q, alpha, beta, nthreads) {
    .Call(`_fast_string_fast_tversky_matrix_impl`, a, b, q, alpha, beta, nthreads)
}

fast_cosine_impl <- function(a, b, q, nthreads) {
    .Call(`_fast_string_fast_cosine_impl`, a, b, q, nthreads)
}

fast_cosine_matrix_impl <- function(a, b, q, nthreads) {
    .Call(`_fast_string_fast_cosine_matrix_impl`, a, b, q, nthreads)
}

